# Generated by Django 5.0.6 on 2024-05-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_category_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'managed': False},
        ),
    ]
