# Generated by Django 5.0.6 on 2024-05-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_delete_category_delete_post_alter_submission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
    ]
